In [1]:
!nvidia-smi

Fri Mar 29 09:13:41 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 415.27       Driver Version: 415.27       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:01:00.0  On |                  N/A |
|  6%   54C    P0    61W / 250W |    511MiB / 11175MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

In [2]:
import torch
from torch import nn

torch.cuda.is_available()

True

In [3]:
torch.cuda.device_count()

1

In [5]:
torch.cuda.current_device()

0

In [6]:
torch.cuda.get_device_name(0)

'GeForce GTX 1080 Ti'

In [10]:
x = torch.tensor([1, 2, 3])
x

tensor([1, 2, 3])

In [11]:
x = x.cuda()
x

tensor([1, 2, 3], device='cuda:0')

In [12]:
x.device

device(type='cuda', index=0)

In [13]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

x = torch.tensor([1, 2, 3], device=device)
# or
x = torch.tensor([1, 2, 3]).to(device)
x

tensor([1, 2, 3], device='cuda:0')

In [14]:
y = x ** 2

In [15]:
z = y + x.cpu()

RuntimeError: expected type torch.cuda.LongTensor but got torch.LongTensor

In [18]:
net = nn.Linear(3, 1)
list(net.parameters())[0].device

device(type='cpu')

In [20]:
net.cuda()
list(net.parameters())[0].device

device(type='cuda', index=0)

In [21]:
x = torch.rand(2,3).cuda()
net(x)

tensor([[-0.3994],
        [-0.5006]], device='cuda:0', grad_fn=<AddmmBackward>)